#-------------------------------
# General Site Settings
title: natsousa
logo: logo_soun.png # You can add own logo.
#description: Zolan is modern minimal theme for Jekyll


#-------------------------------
# Author Settings
author:
  name: Natalia Sousa
  image: 01.jpg
  say-hello: Hello, I’m <strong>Natália Sousa</strong>
  bio: Writes, talks, and enthusiasms about <strong>nature</strong>, <strong>data</strong>, <strong>statistics</strong>, privacy, and dev. I share tutorials, free resources and inspiration. Loves <a href="https://www.youtube.com/watch?v=Ubol9NyLWZc">music</a> & nice meet up.


#-------------------------------
# Contact links
twitter: https://twitter.com/nataliafss
instagram: https://instagram.com/nati.mfs
github: https://github.com/nataliasousa
#facebook: https://facebook.com/ # Add your Facebook handle
#dribbble: https://dribbble.com/ # Add your Dribbble handle
#pinterest: https://pinterest.com/ # Add your Pinterest handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: natsousablog # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: true # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: nati.msf # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: github.us19.list-manage.com/subscribe/post?u=ab50b01b57b114ea3b8d1aa34&amp;id=9935226afd # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
